### ISSUE TITLE
Is the 2018 points history actually counted towards anything in this season's fantasy?

### ISSUE THREAD

**Issue by FozzieHi** [LockeLamora/FridayCityLogic#4]
If it isn't then why are we keeping a log of it in data.json?

`"2018_points_history": [ 19,  37,  37,   7,  31,  20,  36,  19,   0,  23,  33,  17,  37,  38,  23,  37,  31,  22]`

**Comment by LockeLamora** [comment]
Hi!

As it's a new season I tried to get it to be a LITTLE more intelligent than it would've been with the initial team suggestions than it would've been if everyone had 0 points (for example by knowing that Hamilton has a better chance than Albon), but it's definitely just a rough guide and will need your own decisions to intervene (for example Leclerc is expensive this season as a Ferrari driver but the script only has his 2018 Sauber points, so he'd probably never get picked). 

After Melbourne I'll delete the 2018 points as we'll have at least some data to go on, otherwise it's just going to pick pretty nonsense teams pre-melbourne.

**Comment by FozzieHi** [comment]
Oh, fair enough.
